### ISSUE TITLE
Kube-bench-master plugin returns Status: unknown

### ISSUE THREAD

**Issue by CDespeaux** [vmware-tanzu/sonobuoy-plugins#26]
When I run the CIS benchmark in my RKE Kubernetes cluster the Kube-bench-master plugin always returns Status: unknown.  I've tried viewing the detailed results, but none are provided.  How can I figure out what the underlying problem is?  I can run the CIS Benchmark from the Rancher UI and don't see this problem.  Thanks!

$ sonobuoy version --kubeconfig ~/.kube/config 
Sonobuoy Version: v0.18.3
MinimumKubeVersion: 1.16.0
MaximumKubeVersion: 1.18.99
GitSHA: 3e8a10e5145f21840b308b76487f3e10b9c1261d
API Version:  v1.17.4

$ sonobuoy run --plugin plug-ins/kube-bench-master-plugin.yaml --wait
INFO[0000] created object                                name=sonobuoy namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
INFO[0000] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
INFO[0000] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy namespace=sonobuoy resource=pods
INFO[0000] created object                                name=sonobuoy-master namespace=sonobuoy resource=services

$ sonobuoy retrieve
202006221914_sonobuoy_1832bb9a-52a7-4c72-989f-c459a395b4e2.tar.gz

$ sonobuoy results 202006221914_sonobuoy_1832bb9a-52a7-4c72-989f-c459a395b4e2.tar.gz
Plugin: kube-bench-master
Status: unknown
Total: 1
Passed: 0
Failed: 0
Skipped: 0
unknown: 1

$ bin/sonobuoy results 202006221914_sonobuoy_1832bb9a-52a7-4c72-989f-c459a395b4e2.tar.gz --plugin kube-bench-master --mode detailed
{"name":"kube-bench-master","status":"unknown","meta":{"path":"","type":"summary"}}

**Comment by zubron** [comment]
Hi @CDespeaux! Sorry to see you're having problems with this.

I haven't used RKE before, but I just created a single-node cluster using it and tried to run this plugin and saw the same issue. The CIS plugins specify a [node affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity) so that they only run on specific nodes. The `kube-bench-master-plugin.yaml` plugin file [requires the presence of the `node-role.kubernetes.io/master` label](https://github.com/vmware-tanzu/sonobuoy-plugins/blob/master/cis-benchmarks/kube-bench-master-plugin.yaml#L30-L36), and the non-master version [requires the absence of this label](https://github.com/vmware-tanzu/sonobuoy-plugins/blob/master/cis-benchmarks/kube-bench-plugin.yaml#L30-L36).

The RKE cluster that I created did not apply this label to the node that I created. Without this label on any of the nodes, it will fail to schedule the pods for the plugin and so it won't start. I'm not familiar with RKE to know if that label _should_ be applied? Or whether it uses only the `node-role.kubernetes.io/controlplane=true` label. In that case perhaps you could update the `nodeAffinity` in the plugin `PodSpec` to look for that label instead?

Looking at the [Rancher CIS guidance](https://rancher.com/docs/rancher/v2.x/en/security/benchmark-2.1/), it looks like they provide their own hardening guide for their clusters, so you may find that even if you get it to run, the results may differ due to different audits being performed by the underlying tool, kube-bench.

Overall though, there are definitely UX improvements that should be applied to Sonobuoy such as telling the user that it is unable to start the plugin, so I will open an issue in that project.

**Comment by CDespeaux** [comment]
Thanks Bridget!  Setting affinity to this in kube-bench-master-plugin.yaml seems to have resolved it:

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/controlplane
            operator: Exists

**Comment by CDespeaux** [comment]
Closed.
