### ISSUE TITLE
Failed to find /usr/bin/grep

### ISSUE THREAD

**Issue by jessehu** [vmware-tanzu/sonobuoy-plugins#4]
Hello, I'm trying to run sonobuoy cis-benchmarks plugin with this command:

`sonobuoy run --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cis-benchmarks/kube-bench-plugin.yaml --plugin https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/master/cis-benchmarks/kube-bench-master-plugin.yaml --wait
`

It failed at all items using '/bin/ps -ef | grep ... | grep -v grep'. Then I ran 'kube-bench master -v 5 --version 1.15' inside the sonobuoy-kube-bench-master-daemon-set (by adding a long 'sleep' in the container command in the kube-bench-master-plugin.yaml), and saw this error:

`  failed to run: /bin/ps -ef | grep kube-scheduler | grep -v grep, command: [grep -v grep], error: fork/exec /usr/bin/grep: no such file or directory`

After removed the /usr/bin/ mount https://github.com/vmware-tanzu/sonobuoy-plugins/blob/master/cis-benchmarks/kube-bench-master-plugin.yaml#L57-L60, the error is gone. It's because the /usr/bin/grep in my master node VM doesn't work well inside the kube-bench container, and kube-bench  uses the relative path to find 'grep' (https://github.com/aquasecurity/kube-bench/blob/master/cfg/cis-1.5/master.yaml#L919)

I think can remove the /usr/bin/ mount in kube-bench-master-plugin.yaml since '--version' is already set.  We can also file a bug for https://github.com/aquasecurity/kube-bench to replace all 'grep' with '/bin/grep'.

BTW the latest tag of aquasec/kube-bench container is 0.2.2, and it's better to add a note in README.md to tell users to update '--version' in kube-bench-master-plugin.yaml. 

Thanks!

**Comment by zubron** [comment]
Hi @jessehu! I know it's been a long time since you opened this issue, but I thought I'd let you know that we've just updated the CIS plugin and the PR for this (#15) addresses the issues here. The PR:
* Updates the plugin to use the latest version of kube-bench
* Comments out the `/usr/bin` volume definitions/mounts and updates the docs around that to explain why you might use them and how.

I'm going to close this issue, but if you have any other problems or questions, feel free to reopen or create a new issue. Thanks for using the plugin! :)

**Comment by jessehu** [comment]
Thanks @zubron ! The PR solves the problem :)
