### ISSUE TITLE
sonobuoy e2e test keeps waiting and doesn't finish

### ISSUE THREAD

**Issue by eratnch** [vmware-tanzu/sonobuoy-plugins#48]
I am running sonobuoy e2e tests on a bare-metal k8s cluster in certified-conformance mode.

The tests are not finishing and the sonobuoy pods and some objects are not being cleaned up.

I am using sonobuoy 0.18.2 release.

```
12:40:19 + sonobuoy run --plugin e2e -m certified-conformance --context target-cluster --kube-conformance-image gcr.io/google-containers/conformance:v1.18.6 --kubeconfig /root/.airship/kubeconfig --log_dir /tmp/sonobuoy_snapshots/e2e
12:40:19 time="2021-03-16T16:40:28Z" level=info msg="created object" name=sonobuoy namespace= resource=namespaces
12:40:19 time="2021-03-16T16:40:28Z" level=info msg="created object" name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
12:40:19 time="2021-03-16T16:40:28Z" level=info msg="object already exists" name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
12:40:19 time="2021-03-16T16:40:28Z" level=info msg="object already exists" name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterroles
12:40:19 time="2021-03-16T16:40:28Z" level=info msg="created object" name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
12:40:19 time="2021-03-16T16:40:28Z" level=info msg="created object" name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
12:40:19 time="2021-03-16T16:40:28Z" level=info msg="created object" name=sonobuoy namespace=sonobuoy resource=pods
12:40:19 time="2021-03-16T16:40:28Z" level=info msg="created object" name=sonobuoy-master namespace=sonobuoy resource=services
12:40:19 + kubectl get all -n sonobuoy --kubeconfig /root/.airship/kubeconfig --context target-cluster
12:40:19 NAME           READY   STATUS              RESTARTS   AGE
12:40:19 pod/sonobuoy   0/1     ContainerCreating   0          1s
12:40:19 
12:40:19 NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
12:40:19 service/sonobuoy-master   ClusterIP   10.96.112.39   <none>        8080/TCP   1s
12:40:19 + sonobuoy status --kubeconfig /root/.airship/kubeconfig --context target-cluster
12:40:19 time="2021-03-16T16:40:28Z" level=error msg="error attempting to run sonobuoy: pod has status \"Pending\""
12:40:19 Conformance tests have run
12:40:19 listing all sonobuoy components
12:40:19 NAME           READY   STATUS              RESTARTS   AGE
12:40:19 pod/sonobuoy   0/1     ContainerCreating   0          1s
12:40:19 
12:40:19 NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
12:40:19 service/sonobuoy-master   ClusterIP   10.96.112.39   <none>        8080/TCP   1s
```
Any idea on how to check the failed/unfinished tests and why the objects are not being cleaned.

**Comment by johnSchnake** [comment]
So that is not a problem with the e2e test; that is the aggregator pod, sonobuoy itself.

There are lots of reasons something like that might occur, but my first guess would be permissions. I would try to manually run a container of Sonobuoy in a new namespace just to see if it succeeds. You may get some clues by seeing that behavior.  You can also describe the pod and look at more details of the state. Sometimes useful info is elsewhere in the metadata.

If you have more specific questions please feel free to follow up. Otherwise will close this ticket in the next few days.

**Comment by eratnch** [comment]
@johnSchnake , thanks for your reply.
I recreated the cluster and I don't see this issue.
However, if i try to run the tests consecutively it fails with error "preflight checks failed, namespace exists". I am using `sonobuoy delete` command but noticed that it doesn't delete the namespace. 
There's an open issue https://github.com/vmware-tanzu/sonobuoy/issues/1170 on this.
Is there any alternate command that I can use to remove sonobuoy pods and namespace?

**Comment by johnSchnake** [comment]
> I am using sonobuoy delete command but noticed that it doesn't delete the namespace.

It should definitely do that already and typically does (I run this flow very regularly) but in some cases (as the ticket you linked mentions) certain clusters can get into broken states where namespaces never clean up properly.

Some namespaces from the e2e tests themselves can be left around by the e2e tests if there is some issue with them; sonobuoy can clean those up if you say `sonobuoy delete --all` to look for those orphaned namespaces. Sonobuoy isn't in control of those namespaces directly and we don't want to conflict with e2e runs that may be running separately so that isnt the default.

Looking at your quoted output I'm pretty confused;  you run the tests but show their status as being just 1s old and still creating. You don't show a problem with deletion at all.

If you want to attach a full set of logs I am happy to look at it and comment.

**Comment by eratnch** [comment]
Thanks @johnSchnake for your reply.
I am having better results with `sonobuoy delete` after upgrading to sonobuoy version to 0.50.
I think we can close this issue. If I run into this problem again, I'd reopen it and attach all the logs.
