### ISSUE TITLE
Cluster-inventory seems to be no longer working with Sonobuoy 0.55.1

### ISSUE THREAD

**Issue by bemeyert** [vmware-tanzu/sonobuoy-plugins#79]
Hi everybody. 

I want to update Sonobuoy from v0.54.0 to v0.55.1 but our cluster-inventory plugin (v.0.0.2) is failing. In short the error seems to be `error gathering host data: open /tmp/results/results.tar.gz: no such file or directory `. The whole Gist (command and logs) can be found [here](https://gist.github.com/bemeyert/75c2b61f5ae1c13bd890bfba0b0f0f6d).

Any help would be much appreciated.

**Comment by johnSchnake** [comment]
Looks like the issue is probably the mount for the SONOBUOY_RESULTS_DIR.

In some past versions we had issues with different plugins misunderstanding where to put results and such. As a result, Sonobuoy will ensure that each plugin gets the same results directory mounted so that the sidecars know how to work properly.

In this case, the default Sonobuoy config (see sonobuoy gen or sonobuoy gen config) is saying the RESULTS_DIR is `/tmp/sonobuoy/results` but this plugin was written to specify it as `/tmp/results`. That value gets overwritten so that everyone (plugin+worker) is in sync with the config specified. The problem here was that the plugin arguments hardcoded that value.

I'm updating the yaml to use the environment variable to be more robust. Update incoming.

**Comment by johnSchnake** [comment]
Nothing was wrong with the image; you can just update your local yaml file now. The main branch has the fix.

**Comment by bitnik** [comment]
@johnSchnake thanks a lot for the quick fix! But unfortunately cluster-inventory plugin still fails with new sonobuoy image:

```bash
export KUBECONFIG="path/to/kubeconfig"
sonobuoy run \
  --sonobuoy-image="sonobuoy/sonobuoy:v0.55.1" \
  --wait=5 \
  --plugin-image="cluster-inventory:sonobuoy/cluster-inventory:v0.0.2" \
  --plugin=https://raw.githubusercontent.com/vmware-tanzu/sonobuoy-plugins/3dc3bc2e275b1786f737b36136975684b7dba71c/cluster-inventory/cluster-inventory.yaml
```

and the logs from the plugin container of cluster-inventory pod:

```plain
Using CNI config file /etc/cni/net.d/10-canal.conflist
Error: opening sonobuoy report file: open /tmp/sonobuoy/results/sonobuoy_results.yaml: no such file or directory
opening sonobuoy report file: open /tmp/sonobuoy/results/sonobuoy_results.yaml: no such file or directory
Usage:
  cluster-inventory run [flags]

Flags:
  -h, --help                     help for run
      --json-report string       Generate a JSON report at the given path
      --sonobuoy-report string   Generate a Sonobuoy results report at the given path

tar: /tmp/sonobuoy/results/: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar (child): /tmp/sonobuoy/results/results.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
/bin/bash: /tmp/sonobuoy/results/done: No such file or directory
```

**Comment by bitnik** [comment]
Sorry, that was my mistake, the fix is working. Thanks a lot!
